import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#05070B',
  },
  gradient: {
    flex: 1,
  },
  backgroundLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
  },
  asphalt: {
    position: 'absolute',
    width,
    height: '100%',
    opacity: 0.15,
  },
  tireTrack: {
    position: 'absolute',
    width: width * 1.4,
    height: width * 0.9,
    opacity: 0.08,
    tintColor: '#8AFFC1',
  },
  tireTrackTop: {
    top: -40,
    left: -80,
    transform: [{ rotate: '-12deg' }],
  },
  tireTrackBottom: {
    bottom: -80,
    right: -120,
    transform: [{ rotate: '8deg' }],
  },
  carGlow: {
    position: 'absolute',
    width: width * 0.9,
    height: width * 0.45,
    bottom: 80,
    left: -40,
    opacity: 0.14,
    tintColor: '#8AFFC1',
    transform: [{ rotate: '-6deg' }],
  },
  carGhost: {
    position: 'absolute',
    width: width * 0.7,
    height: width * 0.32,
    top: 60,
    right: -50,
    opacity: 0.12,
    tintColor: '#9CA3AF',
    transform: [{ rotate: '10deg' }],
  },
  content: {
    paddingTop: 70,
    paddingBottom: 40,
    paddingHorizontal: 22,
    gap: 22,
  },
  header: {
    gap: 10,
  },
  badge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(138, 255, 193, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(138, 255, 193, 0.25)',
  },
  kicker: {
    color: '#8AFFC1',
    fontSize: 14,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  title: {
    color: '#F9FAFB',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  subtitle: {
    color: '#9CA3AF',
    fontSize: 15,
    lineHeight: 22,
  },
  card: {
    backgroundColor: 'rgba(10, 13, 20, 0.86)',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.35,
    shadowRadius: 40,
    gap: 16,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.04)',
    gap: 12,
  },
  iconChip: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(138, 255, 193, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(138, 255, 193, 0.3)',
  },
  input: {
    flex: 1,
    color: '#E5E7EB',
    fontSize: 16,
  },
  consentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#4B5563',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
  },
  checkboxChecked: {
    borderColor: '#8AFFC1',
    backgroundColor: '#8AFFC1',
  },
  consentTextWrapper: {
    flex: 1,
    gap: 2,
  },
  consentLabel: {
    color: '#F3F4F6',
    fontSize: 14,
    fontWeight: '700',
  },
  consentCopy: {
    color: '#9CA3AF',
    fontSize: 13,
  },
  primaryButton: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(138, 255, 193, 0.35)',
  },
  primaryButtonDisabled: {
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  primaryButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
  },
  primaryButtonText: {
    color: '#05070B',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  primaryButtonTextDisabled: {
    color: '#9CA3AF',
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 4,
  },
  footerText: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  footerLink: {
    color: '#8AFFC1',
    fontSize: 14,
    fontWeight: '700',
  },
});

